version: '3.7'

services:
  ps-predict-node-docker-1:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: ps-predict-node-docker-1
    command: yarn dev